version: "3"

services:

  backend:
    build: ./backend
    image: malwarebytes-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
    environment:
      - PORT=8000
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
      - DATABASE_URI=mongodb://mongo_db:27018/malwarebytes_data
      - TOKEN_SECRET=4ukI0uIVnB3iI1yxj646fVXSE3ZVk4doZgz6fTbNg7jO41EAtl20J5F7Trtwe7OM

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://localhost:8000
        - VITE_BACKEND_SOCKET=ws://localhost:8000
    image: malwarebytes-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo_db:
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27017"
